import { Encode_Sans, Encode_Sans_SC } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../lib/registry";
import { Header } from "../components/layout/Header";
import { Footer } from "../components/layout/Footer";
import { GlobalStylesProvider } from "../components/providers/GlobalStylesProvider";

const EncodeSans = Encode_Sans({
  subsets: ["latin"],
  variable: "--font-encode-sans",
});

const EncodeSC = Encode_Sans_SC({
  subsets: ["latin"],
  variable: "--font-encode-sans-sc",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${EncodeSC.variable}`}>
      <body className={EncodeSans.className}>
        <StyledComponentsRegistry>
          <GlobalStylesProvider>
            <Header />
            {children}
            <Footer />
          </GlobalStylesProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
